server:
  port: 8081
my.greetings: Hai
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true
  profiles:
    active: dev
  config:
        import: optional:configserver:http://localhost:8888
  application:
      name: Springsecurity

jwt:
  secret: secret123

management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: refresh

